#idées : 
# - server syslog

version: '2'
services:

  base: 
    build: ../images/base

  apache: 
    build: ../images/apache
    depends_on: 
      - base

  bdd:
    build: ../images/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql

  fulltextrss:
    build: ../images/fulltextrss
    volumes:
      - ./logs/fulltextrss:/var/log/apache2
      - ./conf/fulltextrss:/var/cedricconf
    depends_on:
      - apache

  ttrss:
    build: ../images/ttrss
    links:
      - bdd
    volumes:
      - ./logs/ttrss:/var/log/apache2
      - ./conf/ttrss:/var/cedricconf
    depends_on: 
      - bdd
      - apache